---

- name: 'install required packages'
  apt:
    name: ['aptitude', 'fail2ban', 'unattended-upgrades', 'logwatch', 'sendmail-bin', 'sendmail', 'mosh']
    state: present
  tags: [ 'packages' ]

- name: 'set the timezone for the server to be UTC'
  file:
    src: /usr/share/zoneinfo/Europe/Berlin
    dest: /etc/localtime
    state: link
    force: no
  register: timezone

- name: 'reconfigure timezone data'
  shell: dpkg-reconfigure -f noninteractive tzdata
  when: timezone.changed
  
- name: 'adjust APT update intervals'
  copy:
    src: apt_periodic 
    dest: /etc/apt/apt.conf.d/10periodic

- name: 'configure logwatch'
  block:
    - name: set up Postfix to relay mail
      debconf:
        name: postfix
        question: '{{ item.question }}'
        value: '{{ item.value }}'
        vtype: '{{ item.vtype }}'
      with_items:
        - { question: 'postfix/mailname', value: '{{ ansible_fqdn }}', vtype: 'string' }
        - { question: 'postfix/main_mailer_type', value: 'Internet Site', vtype: 'string' }

    - name: email log summary daily
      lineinfile:
        path: /etc/cron.daily/00logwatch
        regexp: "^/usr/sbin/logwatch"
        line: "/usr/sbin/logwatch --output mail --mailto {{ logwatch_email }} --detail high"
        state: present
        create: yes

- name: 'lockdown ssh access'
  block:
  - name: 'change ssh port'
    lineinfile: 
      path: /etc/ssh/sshd_config
      regexp: '^Port\s'
      line: 'Port {{ common_ssh_port }}'
      state: present
    notify: restart ssh
  
  - name: 'disallow password authentication'
    lineinfile:
      path: /etc/ssh/sshd_config
      regexp: '^PasswordAuthentication'
      line: 'PasswordAuthentication no'
      state: present
    notify: restart ssh

  - name: disallow root SSH access
    lineinfile:
      path: /etc/ssh/sshd_config
      regexp: '^PermitRootLogin'
      line: 'PermitRootLogin no'
      state: present
    notify: restart ssh
  
  - name: 'listen on only one internet protocol - IPv4'
    lineinfile:
      path: /etc/ssh/sshd_config
      insertafter: EOF
      line: 'AddressFamily inet'
      state: present
    notify: restart ssh

- name: 'protecting SSH with Fail2ban'
  block:
    - name: create /etc/fail2ban/jail.local file
      template:
        src: jail.local.j2
        dest: /etc/fail2ban/jail.local
      notify: restart fail2ban

- name: 'upgrade all packages to the latest version'
  apt:
    name: "*"
    state: latest
  tags: [ 'packages' ]
