baseurl = "https://loncar.net"
title = "Aleš Lončar"

theme = "hugo-coder"

languagecode = "en"
defaultcontentlanguage = "en"

[pagination]
  pagerSize = 20
enableEmoji = true

[services]
  [services.disqus]
    shortname = "loncar"
  [services.googleAnalytics]
    id = 'G-BEWRHJGSN7'

[params]
    author = "Aleš Lončar"
    description = "Freelance Senior Cloud & DevOps Engineer with 25+ years experience in automation, security, and business transformation"
    keywords = "freelance,cloud devops engineer,automation,security,kubernetes,docker,terraform,ansible,business consultant,ci/cd,cloud transformation"
    info = "Freelance Senior Cloud & DevOps Engineer"
    gravatar = "ales.loncar+github@gmail.com"

    faviconSVG = "/img/favicon.ico"
    favicon_32 = "/img/favicon-32x32.png"
    favicon_16 = "/img/favicon-16x16.png"
    touchIcon = "/img/apple-touch-icon.png"

    additionalContent = "25+ years crafting software solutions | Specializing in cloud automation & security | Empowering business innovation | Midnight baker | Analog photography enthusiast | Slovenian expat"

    dateformat = "January 2, 2006"

    hideCredits = false
    hideCopyright = false

    rtl = false
    # Specify light/dark colorscheme
    # Supported values:
    # "auto" (use preference set by browser)
    # "dark" (dark background, light foreground)
    # "light" (light background, dark foreground) (default)
    colorScheme = "auto"
    # Hide the toggle button, along with the associated vertical divider
    hideColorSchemeToggle = false

    customCSS = ["/css/custom.css"]

    # Series see also post count
    maxSeeAlsoItems = 5

[taxonomies]
  category = "categories"
  series = "series"
  tag = "tags"

[[params.social]]
    name = "LinkedIn"
    icon = "fa-brands fa-linkedin fa-2x"
    weight = 1
    url = "https://www.linkedin.com/in/loncarales/"
[[params.social]]
    name = "Github"
    icon = "fa-brands fa-github fa-2x"
    weight = 2
    url = "https://github.com/loncarales"

[[menu.main]]
name = "About"
weight = 1
url = "/about/"

[[menu.main]]
name = "Blog"
weight = 2
url = "/posts/"

[[menu.main]]
name = "Resume"
weight = 3
url = "/resume/"

[[menu.main]]
name = "Snippets"
weight = 4
url = "/snippets/"

[[menu.main]]
name = "Contact"
weight = 5
url = "/contact/"

[markup]
  defaultMarkdownHandler = "goldmark"
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true
  [markup.highlight]
    noClasses = false
    style = "monokai"
