baseurl = "https://loncar.net"
title = "Aleš Lončar"

theme = "hugo-coder"

languagecode = "en"
defaultcontentlanguage = "en"

paginate = 20
enableEmoji = true

googleAnalytics = "UA-111608998-1"
disqusShortname = "loncar"

[params]
    author = "Aleš Lončar"
    description = "Aleš Lončar's personal website"
    keywords = "blog,developer,devops,personal,docker,kubernetes,openshift,helm,ansible,terraform,jenkins,gitlab,packer,ci/cd"
    info = "Software, Cloud and DevOps Engineer"
    gravatar = "ales.loncar@gmail.com"
    
    favicon_32 = "/images/favicon-32x32.ico"
    favicon_16 = "/images/favicon-16x16.ico"

    additionalContent = "Daytime maker of code | Midnight baker / cook | Analog photography enthusiast | Slovenian expat"

    dateformat = "January 2, 2006"

    hideCredits = false
    hideCopyright = false

    rtl = false
    # Specify light/dark colorscheme
    # Supported values:
    # "auto" (use preference set by browser)
    # "dark" (dark background, light foreground)
    # "light" (light background, dark foreground) (default)
    colorScheme = "light"
    # Hide the toggle button, along with the associated vertical divider
    hideColorSchemeToggle = false

    # Series see also post count
    maxSeeAlsoItems = 5

[taxonomies]
  category = "categories"
  series = "series"
  tag = "tags"

[[params.social]]
    name = "LinkedIn"
    icon = "fa-brands fa-linkedin fa-2x"
    weight = 1
    url = "https://www.linkedin.com/in/loncarales/"
[[params.social]]
    name = "Github"
    icon = "fa-brands fa-github fa-2x"
    weight = 2
    url = "https://github.com/loncarales"

[[menu.main]]
name = "About"
weight = 1
url = "/about/"

[[menu.main]]
name = "Blog"
weight = 2
url = "/posts/"

[[menu.main]]
name = "Resume"
weight = 3
url = "https://flowcv.com/resume/eroq39tbe6"

[[menu.main]]
name = "Snippets"
weight = 4
url = "/snippets/"

[[menu.main]]
name = "Contact"
weight = 5
url = "/contact/"

[markup]
  defaultMarkdownHandler = "goldmark"
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true
