baseurl = "https://loncar.net"
title = "Aleš Lončar"

theme = "hugo-coder"

languagecode = "en"
defaultcontentlanguage = "en"

paginate = 20
canonifyurls = true

pygmentsstyle = "b2"
pygmentscodefences = true
pygmentscodefencesguesssyntax = true

googleAnalytics = "UA-111608998-1"
disqusShortname = "loncar"

[params]
    author = "Aleš Lončar"
    description = "Aleš Lončar's personal website"
    keywords = "blog,developer,devops,personal,docker,kubernetes,openshift,helm,ansible,terraform,jenkins,gitlab,packer,ci/cd"
    info = "Software Engineer / DevOps Advocate"
    avatarurl = "https://www.gravatar.com/avatar/545852330726ca4f5568bc769c5dacc6?s=200"
    
    favicon_32 = "/images/favicon-32x32.ico"
    favicon_16 = "/images/favicon-16x16.ico"

    footercontent = "Daytime maker of code | Midnight baker / cook | Analog photography enthusiast | Wine sipper & Beer lover | Slovenian expat"

    dateformat = "January 2, 2006"

    hideCredits = false
    hideCopyright = false

    rtl = false

    # Use inverted colors
    inverted = false

    # Series see also post count
    maxSeeAlsoItems = 5

    # Custom CSS
    custom_css = ["css/custom.css"]

[taxonomies]
  category = "categories"
  series = "series"
  tag = "tags"

[[params.social]]
    name = "LinkedIn"
    icon = "fab fa-linkedin"
    weight = 1
    url = "https://www.linkedin.com/in/loncarales/"
[[params.social]]
    name = "Github"
    icon = "fab fa-github"
    weight = 2
    url = "https://github.com/loncarales"

[[menu.main]]
name = "About"
weight = 1
url = "/about/"

[[menu.main]]
name = "Blog"
weight = 2
url = "/posts/"

[[menu.main]]
name = "Resume"
weight = 3
url = "/resume/"

[[menu.main]]
name = "Snippets"
weight = 4
url = "/snippets/"

[[menu.main]]
name = "Contact"
weight = 5
url = "/contact/"
