# Generated by Terragrunt. Sig: nIlQXj57tbuaRZEa
terraform {
  backend "s3" {
    bucket         = "opentofu-state-c3lavk0"
    dynamodb_table = "opentofu-state-c3lavk0-locks"
    encrypt        = true
    key            = "loncar_net/terraform.tfstate"
    region         = "eu-central-1"
  }
}
