---

- name: Provision Debian Stretch
  hosts: all
  become: yes
  gather_facts: yes

  roles:
    - bootstrap
    
    - remote-user

    - role: server-hardening
      logwatch_email: youremail@example.com
