name: publish-aws-s3

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

env:
  AWS_REGION: eu-central-1

jobs:
  build-and-deploy:
    name: Build and Deploy public artifact to S3 bucket
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v4
        with:
          submodules: true  # Fetch Hugo themes (true OR recursive)
          fetch-depth: 0    # Fetch all history for .GitInfo and .Lastmod

      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v2
        with:
          hugo-version: '0.142.0'
          extended: true

      - name: Build static pages
        run: hugo --minify --logLevel info

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.S3_ACCESS_KEY }}
          aws-secret-access-key: ${{ secrets.S3_SECRET_KEY }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Sync public/ to S3 with proper MIME types
        run: |
          aws s3 sync public/ s3://loncar.net \
            --delete \
            --acl public-read \
            --cache-control "public, max-age=31536000, immutable"
